In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./keybert_keywords.csv')
df.head()

,query,sql,natural_answer,natural_answer_clean,keywords
0,경주시 37세 남자 서비스 혜택 알고 싶어요.,"SELECT benefit_summary, benefit_details, keywo...",경주시의 37세 남성에게 적합한 서비스 혜택으로는 가축 사육 및 축산시설물을 운영하...,경주시의 37세 남성에게 적합한 서비스 혜택으로는 가축 사육 및 축산시설물을 운영하...,"가축재해보험이, 경주시의, 농업인에게"
1,현재 받을 수 있는 지원금은 무엇이 있나요?,SELECT * FROM benefits WHERE start_date <= CUR...,현재 받을 수 있는 지원금에는 다음과 같은 것이 있습니다:\n\n1. **수산업경영...,현재 받을 수 있는 지원금에는 다음과 같은 것이 있습니다: 수산업경영회생자금 지원:...,"관광사업체, 의료기관, 평생교육바우처"
2,장애인을 위한 지원 혜택에는 어떤 것이 있나요?,"SELECT benefit_summary, benefit_details, keywo...",장애인을 위한 지원 혜택에는 여러 가지가 있습니다. 주요 지원 내용은 다음과 같습니...,장애인을 위한 지원 혜택에는 여러 가지가 있습니다. 주요 지원 내용은 다음과 같습니...,"장애학생의, 국립부설학교의, 인신매매와"
3,한부모 가정을 대상으로 하는 지원금은 무엇인가요?,"SELECT benefit_summary, benefit_details, keywo...",한부모 가정을 위한 다양한 지원금 및 혜택이 있습니다. 다음은 해당 지원금 목록입니...,한부모 가정을 위한 다양한 지원금 및 혜택이 있습니다. 다음은 해당 지원금 목록입니...,"한부모가족의, 저소득층, 목록입니다"
4,청년층을 위한 생활안정 지원은 어떤 프로그램이 있나요?,"SELECT benefit_summary, benefit_details, keywo...","청년층을 위한 생활안정 지원 프로그램으로는 여러 가지가 있습니다. 예를 들어, 주택...","청년층을 위한 생활안정 지원 프로그램으로는 여러 가지가 있습니다. 예를 들어, 주택...","생활안정, 주택도시기금에서, 청년층이"

In [3]:
with open("./stopwords-ko.txt", "r", encoding="utf-8") as f:
    korean_stopwords = set([line.strip() for line in f if line.strip()])

In [4]:
def clean_keywords(keyword_str, stopwords):
    keywords = [kw.strip() for kw in keyword_str.split(",")]
    cleaned = [kw for kw in keywords if all(sw not in kw for sw in stopwords)]
    return ", ".join(cleaned)

In [5]:
df["keywords_cleaned"] = df["keywords"].apply(lambda x: clean_keywords(x, korean_stopwords))

In [6]:
df.head()

,query,sql,natural_answer,natural_answer_clean,keywords,keywords_cleaned
0,경주시 37세 남자 서비스 혜택 알고 싶어요.,"SELECT benefit_summary, benefit_details, keywo...",경주시의 37세 남성에게 적합한 서비스 혜택으로는 가축 사육 및 축산시설물을 운영하...,경주시의 37세 남성에게 적합한 서비스 혜택으로는 가축 사육 및 축산시설물을 운영하...,"가축재해보험이, 경주시의, 농업인에게",
1,현재 받을 수 있는 지원금은 무엇이 있나요?,SELECT * FROM benefits WHERE start_date <= CUR...,현재 받을 수 있는 지원금에는 다음과 같은 것이 있습니다:\n\n1. **수산업경영...,현재 받을 수 있는 지원금에는 다음과 같은 것이 있습니다: 수산업경영회생자금 지원:...,"관광사업체, 의료기관, 평생교육바우처",
2,장애인을 위한 지원 혜택에는 어떤 것이 있나요?,"SELECT benefit_summary, benefit_details, keywo...",장애인을 위한 지원 혜택에는 여러 가지가 있습니다. 주요 지원 내용은 다음과 같습니...,장애인을 위한 지원 혜택에는 여러 가지가 있습니다. 주요 지원 내용은 다음과 같습니...,"장애학생의, 국립부설학교의, 인신매매와",
3,한부모 가정을 대상으로 하는 지원금은 무엇인가요?,"SELECT benefit_summary, benefit_details, keywo...",한부모 가정을 위한 다양한 지원금 및 혜택이 있습니다. 다음은 해당 지원금 목록입니...,한부모 가정을 위한 다양한 지원금 및 혜택이 있습니다. 다음은 해당 지원금 목록입니...,"한부모가족의, 저소득층, 목록입니다",목록입니다
4,청년층을 위한 생활안정 지원은 어떤 프로그램이 있나요?,"SELECT benefit_summary, benefit_details, keywo...","청년층을 위한 생활안정 지원 프로그램으로는 여러 가지가 있습니다. 예를 들어, 주택...","청년층을 위한 생활안정 지원 프로그램으로는 여러 가지가 있습니다. 예를 들어, 주택...","생활안정, 주택도시기금에서, 청년층이",생활안정

In [7]:
df[["keywords", "keywords_cleaned"]].head(10)

                 keywords keywords_cleaned
0    가축재해보험이, 경주시의, 농업인에게
1    관광사업체, 의료기관, 평생교육바우처
2   장애학생의, 국립부설학교의, 인신매매와
3     한부모가족의, 저소득층, 목록입니다            목록입니다
4    생활안정, 주택도시기금에서, 청년층이             생활안정
5         친환경적인, 친환경, 창업과       친환경적인, 친환경
6     신청하는, 방식입니다, 이루어집니다            방식입니다
7  기초생활수급자, 평생교육시설, 저소득층을
8       반환보증의, 저소득층의, 이상의
9    주택금융공사를, 주거안정, 직접적으로             주거안정